services:
  db:
    image: postgres:18.3-trixie
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - db-data:/var/lib/postgresql
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data: